### ISSUE TITLE
intermittent unit test failure

### ISSUE THREAD

**Issue by danmarsden** [ArloSoftware/moodle-enrol_arlo#102]
1) enrol_arlo_privacy_provider_testcase::test_get_users_in_context
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => '192000'
-    1 => '192001'
+    0 => 192001
+    1 => 192000
 )

I'm guessing the fix might be to add an order by statement to your get_users_in_context function.

**Comment by troywilliams** [comment]
Thanks for reporting, will investigate.

**Comment by danmarsden** [comment]
I ended up dropping in the following code to make it more reliable for us (probably a lot of different ways to do something similar.):
```
        $userids = $userlist->get_userids();
        asort($userids);
        $this->assertEquals([$user1->id, $user2->id], array_values($userids));

**Comment by troywilliams** [comment]
Thanks, Dan. I have this on the radar to include in next release, will look at incorporating your code and testing later in the week. Thanks, dude :-)

**Comment by troywilliams** [comment]
Fixed at https://github.com/ArloSoftware/moodle-enrol_arlo/pull/105
