### ISSUE TITLE
enrol update_instance events override local changes to enrol config

### ISSUE THREAD

**Issue by danmarsden** [ArloSoftware/moodle-enrol_arlo#112]
If an admin decides to change the settings of an arlo enrolment so that it doesn't send the welcome email, when the event_updated event triggers it then triggers enrol_arlo_handle_update which overwrites the instance config to use the default values hard-coded in lib.php::get_instance_defaults() - looks like the only values kept are arlotype/arloevent but all others are overridden..

enrol_arlo_handle_update() should be adjusted so that it does not overwrite local changes to the enrolment plugin.

**Comment by troywilliams** [comment]
Hey Dan,

Thanks for reporting. Looking at the code, I am unsure whats purpose is. 

Cheers

**Comment by troywilliams** [comment]
Hey Dan,

Issue resolved at https://github.com/ArloSoftware/moodle-enrol_arlo/pull/116. A release will be made available later this week.

Thanks for reporting.

Cheers 🍻
