### ISSUE TITLE
Exception when running sync task - Call to a member function to_record() on boolean

### ISSUE THREAD

**Issue by emyb** [ArloSoftware/moodle-enrol_arlo#120]
Issue reported where synchronization of Arlo data is throwing an exception causing all other arlo syncs and moodle cron to fail.

This occurs when a user is deleted in moodle before the Arlo sync task can process the registration cancellation. 

To replicate the issue:

1. Create an event in Arlo.
2. Register a contact to the event.
3. Create a course in moodle and add an Arlo enrolment instance for the event registration
4. Sync the enrolments in moodle.
5. Delete the user in moodle.
6. Cancel the contact event registration in Arlo.
7. Sync the arlo enrolment instance, run the Synchronization of Arlo data Task manually, or run Moodle cron.

<img width="1559" alt="Screen Shot 2019-08-29 at 9 57 30 AM" src="https://user-images.githubusercontent.com/28742087/63898464-357a2280-ca4d-11e9-97a0-6bb5d7c340e7.png">

<img width="1509" alt="Screen Shot 2019-08-29 at 10 51 15 AM" src="https://user-images.githubusercontent.com/28742087/63898466-357a2280-ca4d-11e9-971e-dfee45f451f3.png">

To prevent this from happening, don't delete users in moodle. If they don't require access then suspend their access.

**Comment by troywilliams** [comment]
Donald
Thanks for reporting the issue, testing details and supplying the fix.
🥇 👍
