### ISSUE TITLE
Failing unit tests: 404 errors at https://phpunit.arlo.co/api

### ISSUE THREAD

**Issue by kristian-94** [ArloSoftware/moodle-enrol_arlo#140]
Running unit tests in a clean moodle 3.7 results in 6 similar errors, I'll paste the first one below:

> root@25a2c29b4867:/siteroot#  vendor/bin/phpunit "enrol_arlo_privacy_provider_testcase" enrol/arlo/tests/privacy_provider_test.php
> Moodle 3.7.4+ (Build: 20200130), e1a6765f6615fcc7a8733718c883d02048751087
> Php: 7.2.19.0.0.18.04.2, pgsql: 11.1 (Debian 11.1-1.pgdg90+1), OS: Linux 4.15.0-88-generic x86_64
> PHPUnit 7.5.17 by Sebastian Bergmann and contributors.
> 
> EEEEEE                                                              6 / 6 (100%)
> 
> Time: 12.92 seconds, Memory: 60.25 MB
> 
> There were 6 errors:
> 
> 1) enrol_arlo_privacy_provider_testcase::test_get_contexts_for_userid
> Unexpected debugging() call detected.
> Debugging: Client error: `GET https://phpunit.arlo.co/api/2012-02-01/auth/resources/events/669801170/` resulted in a `404 Not Found` response:
> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
> <html xml (truncated...)
> 
> * line 104 of /enrol/arlo/classes/local/external.php: call to debugging()
> * line 153 of /enrol/arlo/classes/local/external.php: call to enrol_arlo\local\external::get_resource()
> * line 301 of /enrol/arlo/lib.php: call to enrol_arlo\local\external::update_contenturi()
> * line 217 of /enrol/arlo/tests/generator/lib.php: call to enrol_arlo_plugin->add_instance()
> * line 66 of /enrol/arlo/tests/privacy_provider_test.php: call to enrol_arlo_generator->create_event_enrolment_instance()
> * line 1154 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to enrol_arlo_privacy_provider_testcase->test_get_contexts_for_userid()
> * line 842 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestCase->runTest()
> * line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit\Framework\TestCase->runBare()
> * line 693 of /vendor/phpunit/phpunit/src/Framework/TestResult.php: call to advanced_testcase->runBare()
> * line 796 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestResult->run()
> * line 746 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestCase->run()
> * line 652 of /vendor/phpunit/phpunit/src/TextUI/TestRunner.php: call to PHPUnit\Framework\TestSuite->run()
> * line 206 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\TestRunner->doRun()
> * line 162 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\Command->run()
> * line 61 of /vendor/phpunit/phpunit/phpunit: call to PHPUnit\TextUI\Command::main()
> Debugging: Client error: `PUT https://phpunit.arlo.co/api/2012-02-01/auth/resources/events/669801170/integrationdata/arlomoodleplugin` resulted in a `404 Not Found` response:
> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
> <html xml (truncated...)
> 
> * line 249 of /enrol/arlo/classes/local/external.php: call to debugging()
> * line 303 of /enrol/arlo/lib.php: call to enrol_arlo\local\external::update_manageuri()
> * line 217 of /enrol/arlo/tests/generator/lib.php: call to enrol_arlo_plugin->add_instance()
> * line 66 of /enrol/arlo/tests/privacy_provider_test.php: call to enrol_arlo_generator->create_event_enrolment_instance()
> * line 1154 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to enrol_arlo_privacy_provider_testcase->test_get_contexts_for_userid()
> * line 842 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestCase->runTest()
> * line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit\Framework\TestCase->runBare()
> * line 693 of /vendor/phpunit/phpunit/src/Framework/TestResult.php: call to advanced_testcase->runBare()
> * line 796 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestResult->run()
> * line 746 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestCase->run()
> * line 652 of /vendor/phpunit/phpunit/src/TextUI/TestRunner.php: call to PHPUnit\Framework\TestSuite->run()
> * line 206 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\TestRunner->doRun()
> * line 162 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\Command->run()
> * line 61 of /vendor/phpunit/phpunit/phpunit: call to PHPUnit\TextUI\Command::main()
> 
> 
> /siteroot/lib/phpunit/classes/advanced_testcase.php:88
> 
> To re-run:
>  vendor/bin/phpunit "enrol_arlo_privacy_provider_testcase" enrol/arlo/tests/privacy_provider_test.php

I can't reach https://phpunit.arlo.co/api/2012-02-01/auth/resources/events/707656069/ , I get a 404. Is this a temporary issue? Has the content moved? 
We shouldn't need to reach out to an external service in a unit test. It should just use mocked data.

**Comment by troywilliams** [comment]
Yep, that a bug. For now, the workaround would be to put 
```
$CFG->forced_plugin_settings['enrol_arlo']['allowportalintegration'] = false;
```
in your config.php

**Comment by troywilliams** [comment]
Fixed at https://github.com/ArloSoftware/moodle-enrol_arlo/commit/b57887af349bb8e123787242616dff4ff84ba135
