### ISSUE TITLE
DB schema misaligned: upgrade.php script does not match install.xml

### ISSUE THREAD

**Issue by kristian-94** [ArloSoftware/moodle-enrol_arlo#141]
When installing an older version of the plugin and then updating, the upgrade.php script runs to change our DB schema. For this plugin it leaves the schema in a different state than a fresh install would. 

For example, here: https://github.com/ArloSoftware/moodle-enrol_arlo/blob/master/db/upgrade.php#L169
We add usermodified and timecreated fields to the enrol_arlo_templateassociate table. 

Installing the plugin from scratch would not add these fields to the table however, because they are missing from install.xml:
https://github.com/ArloSoftware/moodle-enrol_arlo/blob/master/db/install.xml#L216

This is a major issue and will cause a lot of errors when people try to install the fresh plugin. It looks like the upgrade script is correct, and the install.xml needs to be updated to match.

**Comment by kristian-94** [comment]
In my moodle env, after upgrading arlo, this is the output from `php admin/cli/check_database_schema.php`

> -------------------------------------------------------------------------------
> enrol_arlo_contact
>  * column 'errorcounter' length is 4, expected at least 10 (I)
> -------------------------------------------------------------------------------
> enrol_arlo_templateassociate
>  * column 'modified' is missing
>  * column 'timemodified' is not expected (I)
>  * column 'usermodified' is not expected (I)
>  * column 'timecreated' is not expected (I)
> -------------------------------------------------------------------------------

**Comment by troywilliams** [comment]
Hi Kristian,

What is the version of the older plugin you installed first and then the version you upgraded to? 

Cheers

**Comment by kristian-94** [comment]
@troywilliams  you can install any version older than 2018100500 (master branch), so that it will run these upgrade.php scripts. After upgrading, it will leave the DB in an incorrect state.

**Comment by troywilliams** [comment]
I have start fix for this at https://github.com/ArloSoftware/moodle-enrol_arlo/compare/master...troywilliams:issue-141 cheers

**Comment by troywilliams** [comment]
Hi Kristian,

The fix has merged and released on Moodle plugins repo.

Thanks again for reporting this.

Troy
