### ISSUE TITLE
core unit test failures due to missing privacy api on enrol_arlo_templateassociate

### ISSUE THREAD

**Issue by danmarsden** [ArloSoftware/moodle-enrol_arlo#145]
FYI - I'm seeing this unit test failure on a 3.9 site.

1) provider_testcase::test_table_coverage
The following tables with user fields must be covered with metadata providers: 
  - enrol_arlo_templateassociate (usermodified)

/var/www/html/privacy/tests/provider_test.php:327
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80
****

**Comment by troywilliams** [comment]
Fixed at https://github.com/ArloSoftware/moodle-enrol_arlo/commit/f5ce1f8175ee2b0a521661b21aeb25d5d9a6978f
