### ISSUE TITLE
'Change registrant' functionality should remove the original registrant and add the new registrant onto the new event

### ISSUE THREAD

**Issue by ArloSoftwareTeam** [ArloSoftware/moodle-enrol_arlo#75]
https://learningsource.zendesk.com/agent/tickets/31507

Steps:
1. Sync an event in Arlo/Moodle
2. On an existing registrant, use the change registrant function
2b. Open an existing order, edit the order and use change registrant function
3. Complete registrant changing
4. Check moodle

EXPECTED:
the original registrant is removed and the new registrant is added onto the new event

ACTUAL:
the original registrant is NOT removed and the new registrant is NOT added onto the new event

**Comment by troywilliams** [comment]
Closing this issue as cannot replicate in the current version of the code.
