### ISSUE TITLE
Registrations not synced to Moodle because of character count conflicts

### ISSUE THREAD

**Issue by ArloSoftwareTeam** [ArloSoftware/moodle-enrol_arlo#78]
**Need to retest other fields as issue may occur not just with PhoneNumber field

Steps:
1. Create a contact in Arlo with PhoneNumber field value of more than 20 characters
2. Add the contact as registrant to any event
3. Sync the event and its registrations to Moodle
4. Check Moodle registrations

EXPECTED:
Registrant with all its values is created in Moodle

ACTUAL:
Registrant is not created in Moodle due to field conflict
*PhoneHome has a 20 char limit, if Arlo data exceeds this. Registrant will not be created in Moodle

** Removed image **

09/08/2018 - Troy - Will be addressed in contact merge fix

**Comment by troywilliams** [comment]
Close as past 18 months.
