### ISSUE TITLE
Disable "Allow unenrol active enrolments"-- user with "active" status  also can be unenrolled

### ISSUE THREAD

**Issue by ArloSoftwareTeam** [ArloSoftware/moodle-enrol_arlo#81]
steps:
1.Disable "Allow unenrol active enrolments"
2.check the enrolment's status is "active "
3.unenrol the user in the report

result:
unenrol successfully

expected result:
unenrol failed and give reminder
![image](https://user-images.githubusercontent.com/12436562/46847304-2643b380-ce40-11e8-9b77-78cfe8c46ac7.png)

**Comment by troywilliams** [comment]
This option was removed from release https://github.com/ArloSoftware/moodle-enrol_arlo/releases/tag/3.5.0
