### ISSUE TITLE
click "unenrol""re-attempt" --no feedback and information, the users don't know if it's successful

### ISSUE THREAD

**Issue by ArloSoftwareTeam** [ArloSoftware/moodle-enrol_arlo#82]
steps:
1.choose the option "allow unenrol accessed"
2.in report click unenrol from arlo linked courses
3.click "re-attempt"

result:
no feedback and reminder
expected result:
give the information to let the user know they "unenrol" from which course; "re-attempt" to which course

**Comment by troywilliams** [comment]
Close as past 18 months.
