### ISSUE TITLE
failing unit tests - missing privacy api.

### ISSUE THREAD

**Issue by danmarsden** [ArloSoftware/moodle-enrol_arlo#88]
Hi Team,

Moodle now implements a new privacy api and includes unit tests to check that all installed plugins contain appropriate privacy classes.

https://docs.moodle.org/dev/Privacy_API

We use Continuous Integration to run all Moodle unit tests prior to deploying any code to our site. Moodle core unit tests are failing with this plugin due to the missing Privacy API. (preventing us from being able to deploy this plugin to a clients 3.5 site.)

Here's the output from the failing unit tests:

1) provider_testcase::test_all_providers_compliant with data set "enrol_arlo" ('enrol_arlo', 'enrol_arlo\privacy\provider')
Failed asserting that false is true.

/var/www/html/privacy/tests/provider_test.php:178
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

2) provider_testcase::test_table_coverage
The following tables with user fields must be covered with metadata providers: 
  - enrol_arlo_contact (userid)
  - enrol_arlo_emailqueue (userid)
  - enrol_arlo_registration (userid)

/var/www/html/privacy/tests/provider_test.php:311
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

thanks,

**Comment by troywilliams** [comment]
Hey Dan,

I will be putting up a new release of the plugin tomorrow on Moodle's plugin repo that includes PrivacyAPI support. 

Cheers,

Troy
