### ISSUE TITLE
all tasks set to run every minute - not great on server performance.

### ISSUE THREAD

**Issue by danmarsden** [ArloSoftware/moodle-enrol_arlo#89]
enrol_arlo\task\synchronize::execute() is set to run by default every minute (eg every cron run)

This task appears to run several different things - site_jobs/scheduled_jobs/expirations/email queue etc and not all appear to be required to run so frequently.

This really needs to be split out into multiple Moodle tasks - so only the really important ones run every minute and the others can be run less frequently.

As these are all already distinct tasks - it would be good to separate each one into it's own Moodle task with appropriate default scheduling.

**Comment by danmarsden** [comment]
splitting the tasks out would also prevent blocking - (I see email queue can has some extra code that allows it to be excluded to prevent blocking, requiring a separate manual cron task to be created on the server.) The better way to do this would be to implement it as a separate Moodle task, because Moodle cron already takes care of this when tasks are individual - typically a long running cron task will not block the next scheduled cron from running.

**Comment by troywilliams** [comment]
Daily 5am cron setup for cleanup tasks like requestlog deletes. https://github.com/ArloSoftware/moodle-enrol_arlo/pull/107
Thanks
