### ISSUE TITLE
invalid class names

### ISSUE THREAD

**Issue by danmarsden** [ArloSoftware/moodle-enrol_arlo#90]
classes and functions should be namespaced or use the plugin frankenstyle prefix.

eg the following class names are too generic 
class admin_setting_configemail
class admin_setting_configlockedtext

and this one is wrong too:
class admin_setting_configarlostatus

they should be namespaced within enrol_arlo, or the class names should be prefixed with "enrol_arlo" eg:
enrol_arlo_admin_setting_configemail.

**Comment by troywilliams** [comment]
Fixed at c8350134f561f62041dde73778848ae6c8089a85 

Thanks for reporting
