### ISSUE TITLE
php lint failure - code does not support PHP 7.2

### ISSUE THREAD

**Issue by danmarsden** [ArloSoftware/moodle-enrol_arlo#91]
Just went to deploy this to one of our test sites and ran into a PHP lint error (which we also run automatically prior to code deploy.)

I'm not seeing that same error when running lint on the files locally though and I haven't looked to closely at it yet - just reporting here in case you get a chance to see it and want to look at fixing.

  "changed": false,
  "php_lint.stderr_lines": [
    "PHP Fatal error:  Cannot declare class AssertionError, because the name is already in use in enrol/arlo/vendor/symfony/polyfill-php70/Resources/stubs/AssertionError.php on line 0",
    "PHP Fatal error:  Cannot declare class Error, because the name is already in use in enrol/arlo/vendor/symfony/polyfill-php70/Resources/stubs/Error.php on line 0",
    "xargs: /usr/bin/php7.0: exited with status 255; aborting",
    "xargs: /usr/bin/php7.0: exited with status 255; aborting",
    "PHP Fatal error:  Cannot declare class ArithmeticError, because the name is already in use in enrol/arlo/vendor/symfony/polyfill-php70/Resources/stubs/ArithmeticError.php on line 0",
    "PHP Fatal error:  Cannot declare class DivisionByZeroError, because the name is already in use in enrol/arlo/vendor/symfony/polyfill-php70/Resources/stubs/DivisionByZeroError.php on line 0",
    "grep: write error: Broken pipe"
  ]
}
task 31:

I haven't looked into why this occurs

**Comment by danmarsden** [comment]
Just had another look at this today - it seems that the polyfill lib included in this plugin doesn't support PHP 7.2 and needs to be updated. This is particularly important because the latest Ubuntu LTS release comes with PHP 7.2 and so most servers deploying new versions of Moodle will be doing so with PHP 7.2

**Comment by troywilliams** [comment]
Hey Dan,

Yep, currently working on new a release to include GDPR support which will also include updated guzzle client, property informer, and extractor libraries which will remove old polyfill library. Should be available in two weeks.

Cheers,

Troy

**Comment by danmarsden** [comment]
sounds good! - guzzle is getting a lot of use these days - we've got it in a number of our plugins too - would be nice to see this supported in core, or possibly just a 3rd party plugin to add guzzle support so we don't have to maintain it in each plugin... although I guess that just makes it harder for some people when they have to install "2" plugins instead of just bundling it all in each plugin...

thanks!

**Comment by troywilliams** [comment]
Yep, I had tried to use Moodle curl then PHP curl but didn't quite work for requirements and time constraints. Using guzzle made the code more readable and was fun to use... a lot of functionality. Anyways putting up a new release for plugin tomorrow, if the update hasn't addressed the issue, please reopen or file a new issue.

Thanks,

Troy

**Comment by danmarsden** [comment]
great thanks Troy!
